apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: my-container
        image: sravyap215/flaskapp:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000